### ISSUE TITLE
export timedMap

### ISSUE THREAD

**Issue by huahuayu** [firasdarwish/temap#6]
Hi, I wonder why `timedMap` type is unexportable
https://github.com/firasdarwish/temap/blob/d915b30f10222a8b4e696434535f45072c3062a9/map.go#L29

so I can't extend it like this, would you mind to make it exportable?

```
type Foo temap.TimedMap
```

**Comment by firasdarwish** [comment]
Hi, huahuayu
you got it, now it's exportable
